### PR TITLE
1.4.0

### LINKED ISSUE #152: Check if view is being rendered by Android Studio Layout Preview Editor
Rendering warnings:

The following classes could not be instantiated:
- com.github.stkent.amplify.prompt.DefaultLayoutPromptView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE  Exception Details java.lang.IllegalStateException: You must call initSharedInstance before calling getSharedInstance.   at com.github.stkent.amplify.tracking.Amplify.getSharedInstance(Amplify.java:108)   at com.github.stkent.amplify.prompt.BasePromptView.<init>(BasePromptView.java:116)   at

As the AS Layout Preview Editor has no access to the shared preferences it's necessary to check if view is in "edit mode" using the View.isInEditMode() and avoid those kind of calls that are not available when on "edit mode".

### PR DESCRIPTION
**Pull request by stkent**
#### Issue Link

Closes #152, #110, #111, #116

### CODE REVIEW

File: amplify/src/main/java/com/github/stkent/amplify/prompt/CustomLayoutQuestionView.java [hunk 1]
```diff
@@ -145,4 +140,22 @@ protected View getPositiveButton() {
     protected View getNegativeButton() {
         return negativeButton;
     }
+
+    /**
+     * We are defensive here, because it's not uncommon to make "buttons" out of UI components like
+     * FrameLayouts, say. If we can't cast to a TextView to obtain a setText method, the button text
+     * will be left unchanged.
+     *
+     * @param quoteButtonUnquote the "button" whose text color we wish to set
```
Comment (stkent) [inline amplify/src/main/java/com/github/stkent/amplify/prompt/CustomLayoutQuestionView.java]: Update this line

File: amplify/src/main/java/com/github/stkent/amplify/prompt/DefaultLayoutQuestionView.java [hunk 2]
```diff
@@ -86,13 +85,82 @@ private void setQuoteButtonUnquoteTextColor(
         }
     }
 
+    private void configureTextSizes(
+            @NonNull final DefaultLayoutPromptViewConfig config,
+            @NonNull final TextView subtitleTextView) {
```
Comment (stkent) [inline amplify/src/main/java/com/github/stkent/amplify/prompt/DefaultLayoutQuestionView.java]: Eh, not a huge fan of this...

File: amplify/src/main/java/com/github/stkent/amplify/utils/DisplayUtils.java [hunk 3]
```diff
@@ -21,16 +21,30 @@
...
+            return 0;
+        }
 
         final Resources resources = context.getResources();
         final DisplayMetrics displayMetrics = resources.getDisplayMetrics();
-        return dp * ((float) displayMetrics.densityDpi / DisplayMetrics.DENSITY_DEFAULT);
+        final float floatResult
+                = dp * ((float) displayMetrics.densityDpi / DisplayMetrics.DENSITY_DEFAULT);
+
+        return max(1, round(floatResult));
```
Comment (stkent) [inline amplify/src/main/java/com/github/stkent/amplify/utils/DisplayUtils.java]: Max sure we already return at least 1px!
